### 1. Write a program to search for an element from an array input from the user.
* Summary: Finds a specific character in a given string
* Input: 
    1. string
    2. character
* Output: Found or None

In [5]:
string=input("Enter an array:")
element=input("Enter an element you are willing to find:")
for i in string:
    if(element==i):
        print("Found")
        break

Enter an array:i am fai
Enter an element you are willing to find:m
Found


### 2. Inserting an element into a position of an array. The element and the insertion point are inputs from the user.
* Summary: Insert an element in an array at any given index
* Input: 
    1. array
    2. index number
* Output: updated array

In [10]:
string=[1,2,3,4,5,6,7] #input array
print("Existing String",string)
element=input("What to be inserted:")
index=int(input("Index at which to be inserted:"))
string.insert(index,element)
print("Updated String",string)

Existing String [1, 2, 3, 4, 5, 6, 7]
What to be inserted:5
Index at which to be inserted:3
Updated String [1, 2, 3, '5', 4, 5, 6, 7]
None


### 3. Inserting a number/character into the proper position of an array which is sorted in ascending/descending order.

* Summary: Sorts an array in ascending order and places a given number in such a manner that the order is maintained
* Input: 
    1. array
    2. number
* Output: updated array

In [6]:
array=[7,9,3,6,5,2,9,0,8,2] #input array
array.sort()
element=int(input("Enter value:"))
index=0
for i in array:
    if(element<=i):
        array.insert(index,element)
        break
    index=index+1
print(array)

Enter value:5
[0, 2, 2, 3, 5, 5, 6, 7, 8, 9, 9]


### 4. Deleting an element from an array.
* Summary: Deletes an input element from a given array
* Input: 
    1. element
* Output: updated array

In [21]:
array=[7,9,3,6,5,2,9,0,8,2] #input array
print("Original Array:",array)
element=int(input("Enter value:"))
array.remove(element)
print("Updated Array:",array)

Enter value:7
[9, 3, 6, 5, 2, 9, 0, 8, 2]


### 5. Write a program to find out the maximum, minimum, median and mode of an array of numbers.
* Summary: Determines the maximum, minimum, median and mode of a given array
* Input: 
* Output: maximum, minimum, median and mode

In [11]:
array=[7,9,3,6,5,2,9,0,8,2] #input array

#Max
print("Maximum:",max(array))

#Min
print("Minimum:",min(array))

#Mean
sum=0
for i in array:
    sum=sum+i
mean=sum/len(array)
print("Mean:",mean)

Maximum: 9
Minimum: 0
Mean: 5.1


In [8]:
#Median
if(len(array)%2==0):
    middle_1=int(len(array)/2)
    middle_2=int(len(array)/2)+1
    median=(array[middle_1]+array[middle_2])/2
else:
    median=array[math.ceil(len(array)/2)]
print("Median:",median)

Median: 5.5


In [9]:
#Mode
dict={}
count=0
for i in array:
    for j in array:
        if(i==j):
            count=count+1
    dict[i]=count
    count=0
print("Mode:",end=" ")
max_value = max(dict.values()) 
for i in dict.items():
    if(i[1]==max_value):
        print(i[0],end=" ")

Mode: 9 2 

### 6. Find k-th maximum and k-th minimum from an array.
* Summary: Finds the kth minimum and maximum value in an array
* Input: k
* Output: kth minimum and kth maximum term

In [81]:
arr=[7,10,4,3,20,15] #input array
k=int(input("Enter value of k:"))
asc_arr=sorted(arr)
desc_arr=sorted(arr,reverse=True)
print("Kth min term",asc_arr[k-1])
print("Kth max term",desc_arr[k-1])

Enter value of k:3
Kth min term 7
Kth max term 10


### 7. Write a program to delete duplicate elements from an array.
* Summary: Finds the duplicate of a term and deletes it
* Input: 
* Output: updated array

In [99]:
array=[7,9,3,6,5,2,9,0,8,2] #input array
dict={}
count=0
for i in array:
    for j in array:
        if(i==j):
            count=count+1
    dict[i]=count #stores the number of times an element is found, and the element is taken as key
    count=0
for i in dict.items():
    if(i[1]>=2):
        for j in range(1,i[1]):
            array.remove(i[0])
            
print(array)

[7, 3, 6, 5, 9, 0, 8, 2]


### 8. Write a program to find the common characters from two arrays.
* Summary: Finds common characters between two arrays
* Input: 
* Output: outputs all the common characters 

In [102]:
array1=[7,9,3,6,5,2,9,0,8,2] #input array 1
array2=[10,11,12,13,14,12,9,0,8,2] #input array 2
dict={}
count=0
for i in array1:
    for j in array2:
        if(i==j):
            count=count+1
    dict[i]=count
    count=0
for i in dict.items():
    if(i[1]>=1):
        print(i[0])
            
#print(array)

9
2
0
8


### 9. Take a string as input and print the characters in reverse order. Don’t use any built in string function.
* Summary: Reverses a given string 
* Input: string
* Output: outputs the string in reverse order

In [105]:
string=input("Enter a string:")
rev_string=""
for i in string:
    rev_string=i+rev_string
print(rev_string)

Enter a string:i am fai
iaf ma i


### 10. Write a program to merge two arrays removing the duplicate elements.
* Summary: Removes the duplicates between two arrays and merges them
* Input: 
* Output: outputs the updtaes merged array

In [113]:
array1=[7,9,3,6,5,2,9,0,8,2] #input array 1
array2=[10,11,12,13,14,12,9,0,8,2] #input array 2
first_array=set(array1) #converts to set
second_array=set(array2) #converts to set

 #subtracts one from the other to remove the common elements
removing_duplicates_array2=second_array-first_array

#merges the updated array2 with array 1
first_array.update(removing_duplicates_array2) 

print(list(first_array))

[0, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


### 11. Take a string as input and check whether it is a Palindrome. If it is not a palindrome, then add minimum no. of character after the string to convert it into a palindrome.
* Summary: Checks to see if a string is palindrome, if not then converts it into one
* Input: string
* Output: 
    1. States "palndrom" if string is palyndrom 
    2. else prints the converted palindrom

In [120]:
string="dro"
rev_string=""
def string_rev(string):
    rev_string=""
    for i in string:
        rev_string=i+rev_string
    return rev_string
    
rev_string=string_rev(string)   
if(string==rev_string):
    print("plaindrom")
else:
    for i in range(1,len(rev_string)):
        string=string+rev_string[i]
        if(string==string_rev(string)):
            break
        

print(string)        

drord


### 12. Write a program to merge two sorted arrays.
* Summary: Merges and sorts two arrays
* Input: 
* Output: opdated merged array

In [1]:
test_list1 = [1, 5, 6, 9, 11]
test_list2 = [3, 4, 7, 8, 10]
   
# to combine two sorted lists
res = sorted(test_list1 + test_list2)
  
print ("The combined sorted list is : " + str(res))

The combined sorted list is : [1, 3, 4, 5, 6, 7, 8, 9, 10, 11]


### 13. Write a program to count the frequencies of each character present in a text. (In addition to alphabet letters, count also the space, tab and punctuation letters)
* Summary: Counts the number of times a character apears in a string 
* Input: string
* Output: Count of all characters

In [2]:
# initializing string 
test_str = "A testingstring"
  

# of each element in string 
all_freq = {}
  
for i in test_str:
    if i in all_freq:
        all_freq[i] += 1
    else:
        all_freq[i] = 1
  


print ("Count of all characters:"+  str(all_freq))

Count of all characters:{'A': 1, ' ': 1, 't': 3, 'e': 1, 's': 2, 'i': 2, 'n': 2, 'g': 2, 'r': 1}


### 14. Write a program to count the number of letters and words within a text.
* Summary: Counts the total number of words and characters present in a string 
* Input:
* Output: 
    1. Total number of words
    2. Total number of characters 

In [7]:
test_str = "A testing string"


words=(test_str.split())
print("Number of words",len(words))

count=0
for i in test_str:
    count=count+1
    if(i==' '):
        count=count-1
        
print("Number of characters",count)

Number of words 3
Number of characters 14


## 15. Write a program which will search for a substring within a string.
* Summary: Searches for a substring in a string 
* Input: 
* Output: 
    1. Prints found if found
    2. else nothing


In [8]:
test_str = "A testing string"

word="string"
sentence=(test_str.split())

for i in sentence:
    if(i==word):
        print('found')

found


### 16. Take n numbers as input from the user. Find out their GCD (Greatest Common Divisor) and LCM (Least Common Multiple).
* Summary: Determines LCM and GCD 

* Function: find_gcd
* Input: two numbers taken from the array
* Output: prints gcd

In [4]:
def find_gcd(num1,num2):
    # the greate number is set as num while the other is set as denominator
    if(num1>num2):
        num=num1
        den=num2
    else:
        num=num2
        den=num1
        
    #the remainder obtained from the num and denominator is stored 
    rem=num%den
    
    #is performed until remainder=0 is obtained
    while(rem!=0):
        num=den
        den=rem
        rem= num%den
        
    gcd = den

    return gcd


array = [2, 4, 6, 8, 16]
 
num1 = array[0]
num2 = array[1]
gcd = find_gcd(num1, num2)
 
for i in range(2, len(array)):
    gcd = find_gcd(gcd, array[i])
     
print(gcd)

2


* Function: find_lcm
* Input: two numbers taken from the array
* Output: prints lcm

In [12]:
def find_lcm(num1,num2):
    # the greate number is set as num while the other is set as denominator
    if(num1>num2):
        num=num1
        den=num2
    else:
        num=num2
        den=num1
        
    #the remainder obtained from the num and denominator is stored 
    rem=num%den
    
    #is performed until remainder=0 is obtained
    while(rem!=0):
        num=den
        den=rem
        rem= num%den
        
    gcd = den
    
    #converting gcd to lcm
    lcm = int(int(num1*num2)/int(gcd))
    return lcm
     
array = [2, 7, 3, 9, 4]
 
num1 = array[0]
num2 = array[1]
lcm = find_lcm(num1, num2)
 
for i in range(2, len(array)):
    lcm = find_lcm(lcm, array[i])
     
print(lcm)

252


### 17. Write a program to Add/Subtract two different Matrices, input from the user.

* Summary: Adds and subtracts two matrices 
* Input:
    1. numbe of rows
    2. number of columns
    3. matrix 1
    4. matrix 2
* Output: 
    1. Summation of the two matrix 
    2. Subtraction of one matrix from the other 

In [11]:
import numpy as np

row = int(input("Enter the number of rows:"))
col = int(input("Enter the number of columns:"))

print("Array1-")
print("Enter values rowwise:")

array1=[]
array2=[]

for i in range(row):         
    temp =[]
    for j in range(col):     
         temp.append(int(input()))
    array1.append(temp)

print("Array2-")
print("Enter values rowwise:")

for i in range(row):         
    temp =[]
    for j in range(col):     
         temp.append(int(input()))
    array2.append(temp)
    

sum=np.asarray(array1)+np.asarray(array2)
sub=np.asarray(array1)-np.asarray(array2)

print("Addition:",sum)
print("Subtraction:",sub)

Enter the number of rows:3
Enter the number of columns:3
Array1-
Enter values rowwise:
1
2
3
4
5
6
7
8
9
Array2-
Enter values rowwise:
2
4
5
9
10
12
5
3
9
Addition: [[ 3  6  8]
 [13 15 18]
 [12 11 18]]
Subtraction: [[-1 -2 -2]
 [-5 -5 -6]
 [ 2  5  0]]


### 18. Write a program to Multiply two matrices
* Summary: Multiplies two matrices
* Input: from the previous problem
* Output: Product of two matrices

In [13]:
array1=np.asarray(array1)
array2=np.asarray(array2)

mul=array1*array2
print(mul)

[[ 2  8 15]
 [36 50 72]
 [35 24 81]]


### 19. Write a program to find out the Transpose of a Matrix.
* Summary: Determines the transpose of a matrix
* Input: from the previous problem
* Output: Transpose

In [14]:
T_array1=array1.transpose()
print(T_array1)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### 20. Write a program to find out Determinant of a Matrix.
* Summary: Determines the determinant of a matrix 
* Input: from the previous problem
* Output: Determinant

In [15]:
np.linalg.det(array1)

-9.51619735392994e-16

### 21. Write a program to construct a nxn magic square
* Summary: Constructs a nxn magic square (Brute Force Approach)
* Input: 
* Output: nxn magic square

In [98]:
n=3

#formula to determine the sum value for the respective value of n
all_sum= n*((n**2)+1)/2
flag=0
a=[]

while(flag!=n*3):
    A = np.random.randint(all_sum, size=(n,n))
    
    #checks two see if this random matrix is unique 
    for i in a:
        if np.array_equal(i,A): 
            print('')
        else:
            flag=0
            
            #checks to see if each sum of row is equal to all_sum
            for i in A.sum(0):
                if(i==all_sum):
                    flag=flag+1
            
             #checks to see if each sum of column is equal to all_sum
            for i in A.sum(1):
                if(i==all_sum):
                    flag=flag+1
                    
            #checks to see if each sum of diagonals is equal to all_sum
            if(np.trace(A)==all_sum):
                flag=flag+n
            a.append(A)
            
print()

KeyboardInterrupt: 